---
 # - name: Change SSH port
  
    # lineinfile: dest=/etc/ssh/sshd_config
    #             regexp="^#Port "
    #             line="Port {{ ssh_port }}"
    #             state=present

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PasswordAuthentication"
                line="PasswordAuthentication no"
                state=present

  - name: Disallow root SSH access
    lineinfile: dest=/etc/ssh/sshd_config
                regexp="^PermitRootLogin"
                line="PermitRootLogin no"
                state=present

  - name: Create user
    user: name={{ user_name }} password={{ user_password }} groups=wheel

  - name: Allow wheel users to sudo
    lineinfile: dest=/etc/sudoers
                regexp="^#\s*(%wheel\s+ALL=\(ALL\)\s+NOPASSWD{{':'}}\s+ALL)"
                line="\1" backrefs=yes state=present
  
  - service: name=firewalld enabled=true state=started
  # - firewalld: port={{ ssh_port }}/tcp permanent=true state=enabled immediate=true
  - firewalld: service=http permanent=true state=enabled immediate=true
  - authorized_key: user={{ user_name }} key="{{ lookup('file', '~/.ssh/myserver_id_rsa.pub') }}"
  - name: restart sshd
    service: name=sshd state=reloaded