---
# ansible playbook for installing nginx

- name: install nginx repo
  yum: >
    name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm   

- name: install nginx
  yum: name=nginx

- name: nginx main config file
  template: >
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=0644

- name: nginx http config file
  template: >
    src=nginx.default.conf.j2
    dest=/etc/nginx/conf.d/default.conf
    owner=root
    group=root
    mode=0644

- name: start nginx service
  service: name=nginx state=started enabled=yes
